#!/bin/bash
function usage {
	echo "${SCRIPT##*/} [ cassandra-0.6.5 | hbase-0.20.6 ] other_options..."
	exit 0
}

# determine ycsb home
if [ -h $0 ]; then
	SCRIPT=$(readlink $0)
else
	SCRIPT=$0
fi
YCSB_HOME=`dirname $SCRIPT`/..

# determine database driver
case $1 in
	cassandra*)
		DB_CLIENT=com.yahoo.ycsb.db.CassandraClient6_5
		;;
	hbase*)
		DB_CLIENT=com.yahoo.ycsb.db.HBaseClient
		;;
	membase*)
		DB_CLIENT=com.yahoo.ycsb.db.MembaseClient
		;;
	*)
		usage
		;;
esac

# check that directory for specific database version exists
DB_HOME=$YCSB_HOME/db/$1
if [ ! -d $DB_HOME ]; then
	usage
fi

# discard first command line argument
shift

# set up classpath 
CLASSPATH=$YCSB_HOME/build/ycsb.jar
for file in `ls $DB_HOME/lib/*.jar`; do
	CLASSPATH=$CLASSPATH:$file
done

CMD="java -cp $CLASSPATH com.yahoo.ycsb.Client -db $DB_CLIENT $*"
echo $CMD
$CMD